/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OppgraderRouteImport } from './routes/oppgrader'
import { Route as IndexRouteImport } from './routes/index'

const OppgraderRoute = OppgraderRouteImport.update({
  id: '/oppgrader',
  path: '/oppgrader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oppgrader': typeof OppgraderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oppgrader': typeof OppgraderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oppgrader': typeof OppgraderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oppgrader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oppgrader'
  id: '__root__' | '/' | '/oppgrader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OppgraderRoute: typeof OppgraderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oppgrader': {
      id: '/oppgrader'
      path: '/oppgrader'
      fullPath: '/oppgrader'
      preLoaderRoute: typeof OppgraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OppgraderRoute: OppgraderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
